route:
  group_by: ['cpu']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'telegram-webhook'

receivers:
  - name: 'telegram-webhook'
    webhook_configs:
      - url: "http://telegram:8088/alert"

