pipeline {
    agent {
        label 'docker-worker-node'
    }

    triggers {
        pollSCM('*/5 * * * *')
    }

    stages {
        stage('Build and Push Docker Image') {
            steps {
                script {
                    def dockerImageTag = "${env.BRANCH_NAME}"

                    withCredentials([usernamePassword(credentialsId: 'DOCKERHUB_CREDENTIALS_ID', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                        sh 'docker build -t oleh888/demo-app:${dockerImageTag} .'
                        sh 'docker push oleh888/demo-app:${dockerImageTag}'
                    }
                }
            }
        }
    }
}
