name: Build and push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get project version from pom.xml
        id: get_version
        run: echo "APP_VERSION=$(grep -oP '<version>\K[^<]+' hw11/application/pom.xml)" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        run: |
          cd hw11
          docker build -t oleh888/docker-demo-app:${{ steps.get_version.outputs.APP_VERSION }}  .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push oleh888/docker-demo-app:${{ steps.get_version.outputs.APP_VERSION }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
